name: Lint & Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm ci
      - name: Lint & Test
        run: npm run test
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
